#MACRO LO(VALUE)
(@VALUE & $00FF)
#ENDM

#MACRO HI(VALUE)
((@VALUE & $FF00) >> 8)
#ENDM

#MACRO SET_WORD(ADDRESS,VALUE)
    LDA.#   @LO(@VALUE)
    STA     @ADDRESS
    LDA.#   @HI(@VALUE)
    STA     @ADDRESS+1
#ENDM

@SET_WORD($ABCD,$1234)

JMP START