
VICII_SCREEN_RAM            = $0400
VICII_COLOR_RAM             = $D800

VICII_SCREEN_TEXT_WIDTH     = 40
VICII_SCREEN_TEXT_HEIGHT    = 25

#MACRO VICII_SCREEN_TEXT_LINE(LineNumber)
VICII_SCREEN_RAM + ( VICII_SCREEN_TEXT_WIDTH * @LineNumber )
#ENDM

#MACRO VICII_SCREEN_COLOR_LINE(LineNumber)
VICII_COLOR_RAM + ( VICII_SCREEN_TEXT_WIDTH * @LineNumber )
#ENDM

#MACRO LO(VALUE)
((@VALUE) & $00FF)
#ENDM

#MACRO HI(VALUE)
(((@VALUE) & $FF00 ) >> 8)
#ENDM

#MACRO SET_WORD(ADDRESS,VALUE)
            LDA.#   @LO(@VALUE)
            STA     @ADDRESS
            LDA.#   @HI(@VALUE)
            STA     @ADDRESS+1
#ENDM

#MACRO X(Item)
        @Item + $0100
#ENDM


LABEL:
        LDA             @VICII_SCREEN_TEXT_LINE(0)

        @SET_WORD($FFFE,@VICII_SCREEN_TEXT_LINE(0))


        LDA             @X(@X(@X($4000)))

        @SET_WORD(@X(@X(@X($4000))),@VICII_SCREEN_TEXT_LINE(0))